load(
    "@rules_swift//swift:swift.bzl",
    "swift_library",
)

swift_library(
    name = "view_code_module",
    srcs = glob(["Sources/**/*.swift"]),
    visibility = ["//visibility:public"],
    module_name = "ViewCode",
    tags = ["manual"],
)
